### ISSUE TITLE
Advice on MAST.Galex.Explore reliability?

### ISSUE THREAD

**Issue by jradavenport** [jradavenport/GALEX_Boyajian#2]
I am a bit overwhelmed by the metadata available for the data on the MAST.Galex.Explore tool.

For [this target](http://galex.stsci.edu/GR6/?page=explore&photo=true&objid=3728666168841474091) there lists 3 NUV visits, exp time of 1298.9 sec. However, gPhoton shows 4 visits, exp time closer to 1600 sec.

Is there any reason *not* to trust the NUV flux or mag (or errors) for this star?

cc: @scfleming, @parkus, @bshiao
- others I should reach out to?? I really don't know who to talk to about this...

**Comment by scfleming** [comment]
Pinging @cmillion in case he can get to this before me.  Normally it's something like effective exposure time (taking into account deadtime, shutter, etc.) available vs. nominal exposure time.  You can do a gPhoton measurement of a single visit using gAperture and compare with the MCAT values.  They should agree to within the uncertainties in most cases.  If not, it's clear sign you will have to treat the fluxes with extra caution.

**Comment by scfleming** [comment]
You can look up the apeture size used to get the MCAT GALEX flux, then re-create that using gAperture.  It's not super intuitive which columns in the MCAT to use for that, so if I have time this week I'll take a stab at it and do a direct comparison between gPhoton and gApreture.  We did that for random sources as part of the gPhoton intro. paper, in fact.

**Comment by bshiao** [comment]
looks like 1 AIS observation was missed, that accounts for some of exp time.

![image](https://cloud.githubusercontent.com/assets/6874051/26607012/5519eec6-4562-11e7-8595-5c0914662728.png)

**Comment by scfleming** [comment]
@jradavenport Did you do a search on GALEX ID?  If so, it would only show the tile (in this case, a MIS = medium survey tile) for that particular entry in the MCAT.  Remember the MCAT is not uniquified, so there are actually likely to be two GALEX MCAT IDs corresponding to this target, one from the MIS observations (totally about 1300 seconds) and a *different* GALEX ID when that source was detected in the AIS = shallow tile.  gPhoton does not have this problem, because it operates on the photon event level, and doesn't care which survey photon events came from.  One of it's primary strengths :)

**Comment by cmillion** [comment]
I am, myself, often confused about how visits do or do not show up in those searches. When I query the MCAT on that position using the same SQL cone search that gPhoton uses, I find 4 visits.

The answer to your direct question is that the MCAT values and errors are reliable. gPhoton is also demonstrated to be reliable on a visit-to-visit comparison to the MCAT, but you should always double check any funny stuff in gAperture photometry with a gMap movie that has the same cadence (for, e.g., transient artifacts that gPhoton doesn't have a mechanism to detect).

There is a difference between the effective / absolute exposure time due to the factors @scfleming noted above, but IIRC the MCAT reports "commanded" exposure time. Difference between commanded exposure time and gPhoton exposure time might be due to how gPhoton estimates exposure time (by using the real pointing).

**Comment by scfleming** [comment]
Indeed, if I used the GALEX "Classic" search form (http://galex.stsci.edu/GR6/?page=mastform) and do a search on RA = 301.56435 and DEC = 44.456784 with a search radius of 0.05 arcmin = 3 arcseconds, there are two sources returned:
3728666168841474091 = Tabby's Star detected from the MIS tile
6371584312244963880 = Tabby's Star detected from the AIS tile
Their coordinates differ by a tiny bit, just 0.6 arcseconds, well within GALEX spatial resolution.  So, there's the difference, and as noted above, gAperture don't care 'bout that.

**Comment by jradavenport** [comment]
👍 Awesome, the differences in the exposure time I was seeing seem well explained then!

So now it's on to comparing to other nearby stars to verify this signal isn't some sneaky noise/contaminant/etc...
